
import type { UserInput } from '@/types';

export const RANK_CATEGORIES: UserInput['rankCategory'][] = [
  "OC", "BC_A", "BC_B", "BC_C", "BC_D", "BC_E", "SC", "ST", "EWS"
];

export const GENDERS: { value: UserInput['gender']; label: string }[] = [
  { value: "BOYS", label: "Boys" },
  { value: "GIRLS", label: "Girls" }
];

export const BRANCHES: string[] = [
  "COMPUTER SCIENCE AND ENGINEERING",
  "ELECTRONICS AND COMMUNICATION ENGINEERING",
  "INFORMATION TECHNOLOGY",
  "MECHANICAL ENGINEERING",
  "CIVIL ENGINEERING",
  "ELECTRICAL AND ELECTRONICS ENGINEERING",
  "ARTIFICIAL INTELLIGENCE AND DATA SCIENCE",
  "COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING)",
  "COMPUTER SCIENCE AND BUSINESS SYSTEM",
  "AERONAUTICAL ENGINEERING",
  "AUTOMOBILE ENGINEERING",
  "BIO-MEDICAL ENGINEERING",
  "BIO-TECHNOLOGY",
  "CHEMICAL ENGINEERING",
  "CSE (IOT AND CYBER SECURITY INCLUDING BLOCK CHAIN TECHNOLOGY)",
  "COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)",
  "COMPUTER SCIENCE AND ENGINEERING (IOT)",
  "COMPUTER ENGINEERING(SOFTWARE ENGINEERING)",
  "COMPUTER SCIENCE & DESIGN",
  "DAIRYING",
  "DIGITAL TECHNIQUES FOR DESIGN AND PLANNING",
  "ELECTRONICS AND INSTRUMENTATION ENGINEERING",
  "ELECTRONICS AND COMPUTER ENGINEERING",
  "ELECTRONICS ENGINEERING (VLSI DESIGN AND TECHNOLOGY)",
  "FOOD TECHNOLOGY",
  "GEO INFORMATICS",
  "MECHANICAL (MECHTRONICS) ENGINEERING",
  "METALLURGY AND MATERIAL ENGINEERING",
  "MINING ENGINEERING",
  "PHARMACEUTICAL ENGINEERING",
  "TEXTILE TECHNOLOGY / TEXTILE ENGINEERING",
  "AGRICULTURAL ENGINEERING",
  "ARTIFICIAL INTELLIGENCE", // Added from data
  "BUILDING SERVICES ENGG", // Added from data
  "B.PLANNING" // Added from data
  // Ensure this list is comprehensive or dynamically generated if possible
];

export const ALL_BRANCHES_IDENTIFIER = "ALL";
